Minor uppdates

diff --git a/bash_prompt b/bash_prompt
--- a/bash_prompt
+++ b/bash_prompt
@@ -54,93 +54,109 @@ BOLD_WHITE='[\033[1;37m\]'
 
 ON_RED='[\033[41m\]'
 
+#
 # Detect whether the current directory is a git repository.
+#
 function is_git_repository {
-  git branch > /dev/null 2>&1
+    git branch > /dev/null 2>&1
 }
 
+
+#
 # Determine the branch/state information for this git repository.
+#
 function set_git_branch {
-  # Capture the output of the "git status" command.
-  git_status="$(git status 2> /dev/null)"
+    # Capture the output of the "git status" command.
+    git_status="$(git status 2> /dev/null)"
 
-  # Set color based on clean/staged/dirty.
-  if [[ ${git_status} =~ "working directory clean" ]]; then
-    state="${GREEN}"
-  elif [[ ${git_status} =~ "Changes to be committed" ]]; then
-    state="${YELLOW}"
-  else
-    state="${LIGHT_RED}"
-  fi
-
-  # Set arrow icon based on status against remote.
-  remote_pattern="# Your branch is (.*) of"
-  if [[ ${git_status} =~ ${remote_pattern} ]]; then
-    if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
-      remote="↑"
+    # Set color based on clean/staged/dirty.
+    if [[ ${git_status} =~ "working directory clean" ]]; then
+        state="${GREEN}"
+    elif [[ ${git_status} =~ "Changes to be committed" ]]; then
+        state="${YELLOW}"
     else
-      remote="↓"
+        state="${LIGHT_RED}"
     fi
-  else
-    remote=""
-  fi
-  diverge_pattern="# Your branch and (.*) have diverged"
-  if [[ ${git_status} =~ ${diverge_pattern} ]]; then
-    remote="↕"
-  fi
 
-  # Get the name of the branch.
-  branch_pattern="^# On branch ([^${IFS}]*)"
-  if [[ ${git_status} =~ ${branch_pattern} ]]; then
-    branch=${BASH_REMATCH[1]}
-  fi
+    # Set arrow icon based on status against remote.
+    remote_pattern="# Your branch is (.*) of"
+    if [[ ${git_status} =~ ${remote_pattern} ]]; then
+        if [[ ${BASH_REMATCH[1]} == "ahead" ]]; then
+            remote="↑"
+        else
+            remote="↓"
+        fi
+    else
+        remote=""
+    fi
 
-  # Set the final branch string.
-  BRANCH="${state}(${branch})${remote}${COLOR_NONE} "
+    diverge_pattern="# Your branch and (.*) have diverged"
+    if [[ ${git_status} =~ ${diverge_pattern} ]]; then
+        remote="↕"
+    fi
+
+    # Get the name of the branch.
+    branch_pattern="^On branch ([^${IFS}]*)"
+    if [[ ${git_status} =~ ${branch_pattern} ]]; then
+        branch=${BASH_REMATCH[1]}
+    fi
+
+    # Set the final branch string.
+    BRANCH="${state}(${branch})${remote}${COLOR_NONE} "
 }
 
+
+#
 # Return the prompt symbol to use, colorized based on the return value of the
 # previous command.
+#
 function set_prompt_symbol () {
-  if test $1 -eq 0 ; then
-      PROMPT_SYMBOL="\$"
-  else
-      PROMPT_SYMBOL="${BOLD_RED}\$${COLOR_NONE}"
-  fi
+    if test $1 -eq 0 ; then
+        PROMPT_SYMBOL="\$"
+    else
+        PROMPT_SYMBOL="${BOLD_RED}\$${COLOR_NONE}"
+    fi
 }
 
+
+#
 # Determine active Python virtualenv details.
+#
 function set_virtualenv () {
-  if test -z "$VIRTUAL_ENV" ; then
-      PYTHON_VIRTUALENV=""
-  else
-      PYTHON_VIRTUALENV="${BOLD_BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
-  fi
+    if test -z "$VIRTUAL_ENV" ; then
+        PYTHON_VIRTUALENV=""
+    else
+        PYTHON_VIRTUALENV="${BOLD_BLUE}[`basename \"$VIRTUAL_ENV\"`]${COLOR_NONE} "
+    fi
 }
 
+
+#
 # Set the full bash prompt.
+#
 function set_bash_prompt () {
-  # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
-  # return value of the last command.
-  set_prompt_symbol $?
+    # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
+    # return value of the last command.
+    set_prompt_symbol $?
 
-  # Set the PYTHON_VIRTUALENV variable.
-  set_virtualenv
+    # Set the PYTHON_VIRTUALENV variable.
+    set_virtualenv
 
-  # Set the BRANCH variable.
-  if is_git_repository ; then
-    set_git_branch
-  else
-    BRANCH=''
-  fi
+    # Set the BRANCH variable.
+    if is_git_repository ; then
+        set_git_branch
+    else
+        BRANCH=''
+    fi
 
-  # Set the bash prompt variable.
-  if $I_HAVE_LIGHT_BACKGROUND ; then
-    PS1="${PYTHON_VIRTUALENV}${DARK_GRAY}\u@\h: \w ${BRANCH}${PROMPT_SYMBOL} "
-  else
-    PS1="${PYTHON_VIRTUALENV}\u@\h: \w ${BRANCH}${PROMPT_SYMBOL} "
-  fi
+    # Set the bash prompt variable.
+    if $I_HAVE_LIGHT_BACKGROUND ; then
+        PS1="${PYTHON_VIRTUALENV}${DARK_GRAY}\u@\h: \w ${BRANCH}${PROMPT_SYMBOL} "
+    else
+        PS1="${PYTHON_VIRTUALENV}\u@\h: \w ${BRANCH}${PROMPT_SYMBOL} "
+    fi
 }
+
 
 # Tell bash to execute this function just before displaying its prompt.
 PROMPT_COMMAND=set_bash_prompt
